import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  flexOne: {
    flex: 1,
  },
  bootRoot: {
    flex: 1,
    backgroundColor: "#fffafc",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  bootText: {
    color: "#831843",
    fontWeight: "700",
  },
  pastelBackdrop: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
  },
  noPointerEvents: {
    pointerEvents: "none",
  },
  pastelBlob: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.24,
  },
  pastelBlobBlueTop: {
    width: 220,
    height: 220,
    backgroundColor: "#f9dce9",
    top: -80,
    left: -45,
  },
  pastelBlobPinkRight: {
    width: 260,
    height: 260,
    backgroundColor: "#f8dff0",
    right: -95,
    top: 140,
  },
  pastelBlobBlueBottom: {
    width: 240,
    height: 240,
    backgroundColor: "#f6d6e7",
    bottom: -80,
    left: 70,
  },
  pastelDot: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.42,
  },
  pastelDotOne: {
    width: 12,
    height: 12,
    backgroundColor: "#f3cde5",
    top: 120,
    right: 28,
  },
  pastelDotTwo: {
    width: 9,
    height: 9,
    backgroundColor: "#f2c6db",
    top: 158,
    right: 58,
  },
  pastelDotThree: {
    width: 8,
    height: 8,
    backgroundColor: "#f3cde5",
    top: 198,
    right: 26,
  },
  pastelDotFour: {
    width: 10,
    height: 10,
    backgroundColor: "#efc2d8",
    bottom: 210,
    left: 26,
  },
  pastelDotFive: {
    width: 8,
    height: 8,
    backgroundColor: "#f3cde5",
    bottom: 176,
    left: 52,
  },
  pastelDotSix: {
    width: 12,
    height: 12,
    backgroundColor: "#f4d0e1",
    bottom: 138,
    left: 32,
  },
  pastelDotSeven: {
    width: 9,
    height: 9,
    backgroundColor: "#f1c8df",
    bottom: 98,
    right: 42,
  },
  pastelDotEight: {
    width: 7,
    height: 7,
    backgroundColor: "#f1c7dc",
    bottom: 70,
    right: 72,
  },
  loginRoot: {
    flex: 1,
    backgroundColor: "#fffafc",
    paddingHorizontal: 18,
    paddingTop: 64,
    justifyContent: "center",
  },
  loginCircleOne: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: "#f9e6ec",
    right: -55,
    top: -40,
  },
  loginCircleTwo: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: "#fdeef4",
    left: -60,
    bottom: -20,
  },
  loginCard: {
    borderRadius: 24,
    backgroundColor: "#fffdfd",
    borderWidth: 1,
    borderColor: "#efdbe3",
    padding: 18,
  },
  loginBrand: {
    textAlign: "center",
    fontSize: 30,
    color: "#be185d",
    fontWeight: "900",
    fontFamily: "serif",
    letterSpacing: 1.8,
  },
  loginTitle: {
    textAlign: "center",
    fontSize: 18,
    color: "#ec4899",
    fontWeight: "800",
    marginTop: 8,
    letterSpacing: 1.2,
  },
  loginHint: {
    textAlign: "center",
    color: "#7f4f6f",
    marginTop: 6,
    marginBottom: 6,
    fontSize: 14,
    fontWeight: "600",
  },
  loginApiHint: {
    textAlign: "center",
    color: "#8f5d7b",
    fontSize: 11,
    marginBottom: 12,
  },
  loginInput: {
    backgroundColor: "#fdf1f5",
    borderRadius: 12,
    color: "#6a1234",
    paddingHorizontal: 12,
    paddingVertical: 13,
    marginBottom: 10,
    textAlign: "right",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#efcadb",
  },
  loginButton: {
    marginTop: 6,
    backgroundColor: "#ec4899",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  loginButtonText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 16,
  },
  loginDemoBox: {
    marginTop: 14,
    backgroundColor: "#fdf2f6",
    borderRadius: 12,
    padding: 10,
  },
  loginDemoTitle: {
    color: "#9d174d",
    textAlign: "right",
    fontWeight: "800",
    marginBottom: 4,
  },
  loginDemoText: {
    color: "#935682",
    textAlign: "right",
    fontWeight: "600",
    marginTop: 2,
  },
  loginStatus: {
    marginTop: 10,
    textAlign: "center",
    color: "#7f4f6f",
    fontWeight: "600",
    fontSize: 13,
  },
  appRoot: {
    flex: 1,
    backgroundColor: "#fffafc",
  },
  shell: {
    flex: 1,
    flexDirection: "row-reverse",
  },
  shellMobile: {
    flexDirection: "column",
  },
  mainPane: {
    flex: 1,
    paddingTop: 44,
    paddingHorizontal: 16,
  },
  mainPaneMobile: {
    paddingTop: 22,
    paddingHorizontal: 13,
  },
  mainPanePortraitMobile: {
    paddingTop: 24,
    paddingHorizontal: 14,
  },
  sidebar: {
    width: 168,
    paddingTop: 70,
    paddingHorizontal: 10,
    backgroundColor: "#fceff3",
    borderLeftWidth: 1,
    borderLeftColor: "#efdbe2",
    justifyContent: "flex-start",
    paddingBottom: 22,
  },
  sidebarBrand: {
    textAlign: "center",
    fontSize: 34,
    fontWeight: "900",
    color: "#be185d",
    fontFamily: "serif",
    letterSpacing: 1.8,
  },
  sidebarSubBrand: {
    textAlign: "center",
    marginTop: -4,
    marginBottom: 16,
    color: "#ec4899",
    fontWeight: "800",
    letterSpacing: 1.1,
  },
  sidebarNavScroll: {
    flex: 1,
    minHeight: 0,
    marginTop: 4,
    marginBottom: 12,
  },
  sidebarNav: {
    gap: 8,
    paddingBottom: 8,
  },
  sidebarNavItem: {
    borderRadius: 13,
    paddingVertical: 10,
    paddingHorizontal: 8,
    backgroundColor: "transparent",
  },
  sidebarNavItemActive: {
    backgroundColor: "#f4d9e7",
  },
  sidebarNavText: {
    textAlign: "right",
    color: "#8f4c74",
    fontWeight: "800",
    fontSize: 13,
  },
  sidebarNavTextActive: {
    color: "#9d174d",
  },
  sidebarNavSubText: {
    textAlign: "right",
    color: "#d3aebf",
    fontSize: 11,
    marginTop: 2,
  },
  sidebarNavSubTextActive: {
    color: "#a77097",
  },
  sidebarActionButton: {
    marginTop: "auto",
    backgroundColor: "#ec4899",
    borderRadius: 13,
    paddingVertical: 12,
    alignItems: "center",
  },
  sidebarActionButtonText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 15,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
    gap: 10,
  },
  headerRowMobile: {
    marginBottom: 8,
    gap: 6,
  },
  userBlock: {
    flex: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: "900",
    color: "#be185d",
    textAlign: "right",
    fontFamily: "serif",
    letterSpacing: 1.4,
  },
  titleMobile: {
    fontSize: 22,
    letterSpacing: 1.05,
  },
  subtitleBrand: {
    fontSize: 11,
    color: "#ec4899",
    marginTop: -1,
    textAlign: "right",
    fontWeight: "700",
    letterSpacing: 1,
  },
  subtitleBrandMobile: {
    fontSize: 9,
    marginTop: -2,
    letterSpacing: 0.75,
  },
  subtitle: {
    fontSize: 13,
    color: "#ae7ca1",
    marginTop: 4,
    textAlign: "right",
  },
  subtitleMobile: {
    fontSize: 11,
    marginTop: 2,
  },
  subtitleSmall: {
    fontSize: 11,
    color: "#cfa8c0",
    marginTop: 2,
    textAlign: "right",
  },
  subtitleSmallMobile: {
    fontSize: 9,
    marginTop: 1,
  },
  headerActions: {
    alignItems: "flex-end",
    gap: 8,
  },
  headerActionsMobile: {
    gap: 5,
  },
  headerActionButtonMobile: {
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  headerActionButtonTextMobile: {
    fontSize: 12,
  },
  mobileNavButton: {
    backgroundColor: "#f8e8ee",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mobileNavButtonActive: {
    backgroundColor: "#ec4899",
  },
  mobileNavButtonText: {
    color: "#9d174d",
    fontWeight: "700",
  },
  mobileNavButtonTextActive: {
    color: "#ffffff",
  },
  adminButton: {
    backgroundColor: "#f8e8ee",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  adminButtonText: {
    color: "#9d174d",
    fontWeight: "700",
  },
  badge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  badgeMobile: {
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  badgeOnline: {
    backgroundColor: "#f8e8ee",
  },
  badgeOffline: {
    backgroundColor: "#fdecef",
  },
  badgeText: {
    fontWeight: "700",
    color: "#9d174d",
  },
  badgeTextMobile: {
    fontSize: 12,
  },
  logoutButton: {
    backgroundColor: "#fbe8ee",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  logoutButtonText: {
    color: "#831843",
    fontWeight: "700",
  },
  content: {
    paddingBottom: 40,
  },
  storeRow: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  categoryRow: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
    marginBottom: 4,
  },
  mobilePageRow: {
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  mobilePageCurrentText: {
    width: "100%",
    textAlign: "center",
    color: "#9d174d",
    fontWeight: "800",
    fontSize: 14,
  },
  storeChip: {
    backgroundColor: "#f8e8ee",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  storeChipSelected: {
    backgroundColor: "#ec4899",
  },
  storeChipDisabled: {
    opacity: 0.55,
  },
  storeChipText: {
    color: "#6f1536",
    fontWeight: "700",
    fontSize: 14,
    textAlign: "right",
  },
  storeChipTextSelected: {
    color: "#ffffff",
  },
  storeChipTextDisabled: {
    color: "#c395b5",
  },
  section: {
    backgroundColor: "#fffbfd",
    borderRadius: 18,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#f1e0e7",
  },
  sectionTitle: {
    fontSize: 19,
    fontWeight: "800",
    color: "#7a123a",
    textAlign: "right",
    marginBottom: 12,
  },
  sectionHeaderInline: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    rowGap: 8,
    columnGap: 8,
  },
  productsGrid: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 10,
  },
  posWorkspace: {
    flexDirection: "row-reverse",
    alignItems: "flex-start",
    gap: 12,
  },
  posWorkspaceMobile: {
    flexDirection: "column",
  },
  posProductsColumn: {
    flex: 1,
    minWidth: 0,
  },
  posProductsColumnMobile: {
    width: "100%",
    flex: 0,
  },
  posControlPane: {
    width: 340,
    flexGrow: 0,
    flexShrink: 0,
    gap: 3,
    alignSelf: "flex-start",
    marginTop: -16,
  },
  posControlPaneMobile: {
    width: "100%",
    flex: 0,
    marginTop: 0,
  },
  posProductsPane: {
    width: "100%",
  },
  posProductsPaneMobile: {
    width: "100%",
    flex: 0,
  },
  posSection: {
    padding: 5,
    borderColor: "#f0d3e0",
    boxShadow: "0px 2px 6px rgba(198, 107, 144, 0.06)",
    elevation: 1,
  },
  posPadSection: {
    paddingTop: 14,
    paddingBottom: 4,
  },
  posSectionTitle: {
    fontSize: 13,
    marginBottom: 5,
  },
  posProductsGrid: {
    width: "100%",
    alignSelf: "stretch",
    overflow: "hidden",
  },
  productCardCompact: {
    width: "96%",
    height: "96%",
    maxWidth: "100%",
    maxHeight: "100%",
    alignSelf: "center",
    minWidth: 0,
    backgroundColor: "#fbe8ee",
    borderRadius: 10,
    padding: 5,
    borderWidth: 1,
    borderColor: "#efcad4",
    marginBottom: 0,
    overflow: "hidden",
    justifyContent: "space-between",
  },
  productCardCompactMobile: {
    width: "96%",
    height: "96%",
    minWidth: 0,
  },
  productCardDragging: {
    opacity: 0.92,
    borderColor: "#db2777",
    backgroundColor: "#ffe1ee",
    elevation: 2,
    transform: [{ scale: 1.02 }],
  },
  productCardHeadRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 2,
    flexShrink: 0,
  },
  dragHintText: {
    color: "#9d174d",
    fontWeight: "800",
    fontSize: 9,
    backgroundColor: "#f8e8ee",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#efcad4",
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  productTapArea: {
    borderRadius: 8,
    backgroundColor: "#fff6fa",
    paddingHorizontal: 4,
    paddingVertical: 4,
    flex: 1,
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    justifyContent: "space-between",
    overflow: "hidden",
  },
  productTapAreaDragging: {
    backgroundColor: "#ffe5f0",
  },
  dragHandle: {
    alignSelf: "flex-start",
  },
  productCard: {
    width: "48%",
    backgroundColor: "#fbe8ee",
    borderRadius: 14,
    padding: 10,
  },
  productName: {
    color: "#701a3a",
    fontWeight: "800",
    fontSize: 12,
    lineHeight: 16,
    minHeight: 30,
    textAlign: "right",
    flexShrink: 1,
  },
  productPrice: {
    color: "#db2777",
    marginTop: 4,
    fontWeight: "800",
    fontSize: 12,
    textAlign: "right",
    flexShrink: 0,
  },
  productActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
  },
  smallButtonGhost: {
    width: 36,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ec4899",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fffbfd",
  },
  smallButtonGhostCompact: {
    width: 28,
    height: 24,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "#ec4899",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fffbfd",
  },
  smallButtonGhostText: {
    color: "#ec4899",
    fontWeight: "900",
    fontSize: 15,
  },
  smallButtonSolid: {
    width: 36,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ec4899",
  },
  smallButtonSolidCompact: {
    width: 28,
    height: 24,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ec4899",
  },
  smallButtonSolidText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 15,
  },
  emptyText: {
    color: "#7f4f6f",
    fontSize: 15,
    fontWeight: "600",
    textAlign: "right",
  },
  cartItemRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#f2e2e8",
    paddingVertical: 8,
  },
  cartListContainer: {
    minHeight: 112,
    maxHeight: 260,
  },
  cartListScroll: {
    maxHeight: 260,
  },
  cartItemName: {
    flex: 1,
    color: "#9d174d",
    fontWeight: "600",
    textAlign: "right",
  },
  cartItemQty: {
    width: 52,
    color: "#9a5e88",
    textAlign: "center",
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  cartItemPrice: {
    width: 100,
    color: "#9d174d",
    textAlign: "left",
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  inputRow: {
    flexDirection: "row-reverse",
    gap: 8,
    marginTop: 12,
  },
  input: {
    flex: 1,
    backgroundColor: "#fdf2f6",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    color: "#6a1234",
    textAlign: "right",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#efcadb",
  },
  datePickerInputText: {
    color: "#6a1234",
    textAlign: "right",
    fontSize: 16,
    fontWeight: "600",
  },
  datePickerInputPlaceholder: {
    color: "#d7b3c4",
    textAlign: "right",
    fontSize: 16,
  },
  padDisplayBox: {
    backgroundColor: "#fdf2f6",
    borderRadius: 7,
    paddingVertical: 3,
    paddingHorizontal: 5,
  },
  padDisplayLabel: {
    color: "#b88bad",
    textAlign: "right",
    fontWeight: "600",
    fontSize: 9,
  },
  padDisplayValue: {
    color: "#9d174d",
    textAlign: "right",
    fontWeight: "900",
    fontSize: 14,
    marginTop: 1,
  },
  padMetaRow: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    marginTop: 1,
    marginBottom: 1,
  },
  padMetaText: {
    color: "#ae7ca1",
    fontWeight: "700",
    fontSize: 8.5,
  },
  padGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 3,
  },
  padKey: {
    width: "31%",
    minWidth: 34,
    backgroundColor: "#f8e8ee",
    borderRadius: 6,
    paddingVertical: 3,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#efcad4",
  },
  padKeyKeyboardPressed: {
    backgroundColor: "#f9a8d4",
    borderColor: "#db2777",
    transform: [{ scale: 0.96 }],
  },
  padKeyText: {
    color: "#831843",
    fontWeight: "900",
    fontSize: 12,
    fontVariant: ["tabular-nums"],
  },
  padActionRow: {
    marginTop: 3,
    flexDirection: "row-reverse",
    gap: 3,
  },
  padActionButton: {
    flex: 1,
    backgroundColor: "#f8e8ee",
    borderRadius: 6,
    alignItems: "center",
    paddingVertical: 5,
  },
  padActionButtonPrimary: {
    flex: 1,
    backgroundColor: "#ec4899",
    borderRadius: 6,
    alignItems: "center",
    paddingVertical: 5,
  },
  padActionButtonDanger: {
    backgroundColor: "#fdecef",
    borderWidth: 1,
    borderColor: "#efcad4",
  },
  padActionText: {
    color: "#831843",
    fontWeight: "800",
    fontSize: 10,
  },
  padActionTextPrimary: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 10,
  },
  padClearButton: {
    marginTop: 4,
    backgroundColor: "#fdeef4",
    borderRadius: 6,
    alignItems: "center",
    paddingVertical: 4,
  },
  padClearText: {
    color: "#975985",
    fontWeight: "700",
    fontSize: 10,
  },
  inputFull: {
    marginTop: 6,
    backgroundColor: "#fdf2f6",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
    color: "#6a1234",
    textAlign: "right",
    fontSize: 15,
    borderWidth: 1,
    borderColor: "#efcadb",
  },
  summaryRow: {
    marginTop: 8,
    gap: 3,
  },
  summaryText: {
    color: "#9a5e88",
    fontWeight: "600",
    textAlign: "right",
  },
  summaryTextStrong: {
    color: "#9d174d",
    fontSize: 16,
    fontWeight: "800",
    textAlign: "right",
  },
  primaryButton: {
    marginTop: 8,
    backgroundColor: "#ec4899",
    borderRadius: 12,
    paddingVertical: 9,
    alignItems: "center",
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 15,
  },
  cancelOrderButton: {
    marginTop: 5,
    backgroundColor: "#fdecef",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#efcad4",
    paddingVertical: 8,
    alignItems: "center",
  },
  cancelOrderButtonText: {
    color: "#db2777",
    fontWeight: "800",
    fontSize: 14,
  },
  secondaryButton: {
    marginTop: 12,
    backgroundColor: "#9d174d",
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: "center",
  },
  secondaryButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
  },
  sectionActions: {
    marginTop: 10,
    gap: 8,
  },
  expenseImagePreviewBox: {
    marginTop: 10,
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#efcadb",
    backgroundColor: "#fff6fa",
  },
  expenseImagePreview: {
    width: "100%",
    height: 140,
  },
  expenseImageLargePreview: {
    width: "100%",
    height: 220,
    borderRadius: 12,
    marginTop: 8,
  },
  supplyAddBox: {
    marginTop: 8,
    backgroundColor: "#fff6fb",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#efd4e3",
    padding: 10,
  },
  supplyAddTitle: {
    color: "#9d174d",
    fontWeight: "800",
    textAlign: "right",
    marginBottom: 6,
  },
  supplyActionRow: {
    marginTop: 8,
    flexDirection: "row-reverse",
    gap: 8,
  },
  supplyActionButtonPrimary: {
    flex: 1,
    backgroundColor: "#ec4899",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  supplyActionButtonTextPrimary: {
    color: "#ffffff",
    fontWeight: "800",
  },
  supplyActionButton: {
    flex: 1,
    backgroundColor: "#f8e8ee",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  supplyActionButtonText: {
    color: "#9d174d",
    fontWeight: "800",
  },
  supplyRow: {
    marginTop: 8,
    backgroundColor: "#fff6fa",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#f2dbe6",
    padding: 10,
    gap: 6,
  },
  supplyColumnsHeader: {
    marginTop: 8,
    marginBottom: 2,
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 4,
  },
  supplyColumnsHeaderText: {
    color: "#ae7ca1",
    fontWeight: "700",
    fontSize: 11,
    textAlign: "right",
    width: "33%",
  },
  supplyEmptyState: {
    marginTop: 10,
    gap: 8,
  },
  addProductCtaButton: {
    backgroundColor: "#ec4899",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  addProductCtaButtonText: {
    color: "#ffffff",
    fontWeight: "800",
  },
  addProductInlineButton: {
    marginTop: 8,
    backgroundColor: "#f8e8ee",
    borderWidth: 1,
    borderColor: "#e9c7d6",
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: "center",
  },
  addProductInlineButtonText: {
    color: "#9d174d",
    fontWeight: "800",
  },
  supplyFieldsRow: {
    flexDirection: "row-reverse",
    alignItems: "flex-start",
    gap: 8,
  },
  supplyField: {
    flex: 1,
  },
  supplyFieldLabel: {
    color: "#ae7ca1",
    fontWeight: "700",
    textAlign: "right",
    fontSize: 11,
    marginBottom: 4,
  },
  supplyReadonlyInput: {
    color: "#9d174d",
    backgroundColor: "#f7e7ef",
  },
  supplyLoggedTodayText: {
    color: "#ae7ca1",
    textAlign: "right",
    marginTop: 4,
    fontSize: 11,
    fontWeight: "600",
  },
  supplyInfoBox: {
    flex: 1,
    backgroundColor: "#fdf2f6",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#efd8e3",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  supplyInfoLabel: {
    color: "#ae7ca1",
    fontWeight: "700",
    textAlign: "right",
    fontSize: 11,
  },
  supplyInfoValue: {
    color: "#9d174d",
    fontWeight: "900",
    textAlign: "right",
    marginTop: 2,
    fontSize: 15,
  },
  rowActionButtons: {
    marginTop: 8,
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  dangerButton: {
    backgroundColor: "#fdecef",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  dangerButtonText: {
    color: "#db2777",
    fontWeight: "800",
  },
  smallRefreshButton: {
    backgroundColor: "#f8e8ee",
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  smallRefreshText: {
    color: "#9d174d",
    fontWeight: "700",
  },
  supplyHeaderActions: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  addProductButton: {
    backgroundColor: "#ec4899",
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  addProductButtonText: {
    color: "#ffffff",
    fontWeight: "800",
  },
  addExpenseFromPurchasesButton: {
    marginTop: 8,
    backgroundColor: "#f8e8ee",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e8c9d6",
    paddingVertical: 9,
    alignItems: "center",
  },
  addExpenseFromPurchasesButtonText: {
    color: "#9d174d",
    fontWeight: "800",
  },
  employeeSummaryRow: {
    marginTop: 8,
    backgroundColor: "#fff6fa",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#f2e2e8",
    padding: 10,
    gap: 6,
  },
  settlementStatsGrid: {
    marginTop: 8,
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 8,
  },
  settlementStatCard: {
    width: "48%",
    backgroundColor: "#fdf1f6",
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: "#efd7e3",
  },
  settlementStatLabel: {
    color: "#ae7ca1",
    fontWeight: "700",
    textAlign: "right",
    fontSize: 11,
  },
  settlementStatValue: {
    color: "#9d174d",
    fontWeight: "900",
    textAlign: "right",
    marginTop: 4,
    fontSize: 14,
  },
  settlementStatCardHighlight: {
    width: "98%",
    backgroundColor: "#ec4899",
    borderRadius: 12,
    padding: 11,
  },
  settlementStatLabelHighlight: {
    color: "#fdeff4",
    fontWeight: "700",
    textAlign: "right",
    fontSize: 12,
  },
  settlementStatValueHighlight: {
    color: "#ffffff",
    fontWeight: "900",
    textAlign: "right",
    marginTop: 4,
    fontSize: 18,
  },
  settlementDiffPositive: {
    color: "#be185d",
    textAlign: "right",
    fontWeight: "700",
  },
  settlementDiffNegative: {
    color: "#ec4899",
    textAlign: "right",
    fontWeight: "800",
  },
  settlementDiffNeutral: {
    color: "#9a5e88",
    textAlign: "right",
    fontWeight: "700",
  },
  metricsGrid: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 10,
  },
  metricCard: {
    width: "48%",
    backgroundColor: "#fbe8ee",
    borderRadius: 14,
    padding: 12,
  },
  metricLabel: {
    color: "#ae7ca1",
    fontWeight: "600",
    textAlign: "right",
  },
  metricValue: {
    color: "#9d174d",
    fontWeight: "800",
    fontSize: 18,
    marginTop: 6,
    textAlign: "right",
  },
  metricCardHighlight: {
    width: "48%",
    backgroundColor: "#ec4899",
    borderRadius: 14,
    padding: 12,
  },
  metricLabelHighlight: {
    color: "#fdeff4",
    fontWeight: "600",
    textAlign: "right",
  },
  metricValueHighlight: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 19,
    marginTop: 6,
    textAlign: "right",
  },
  orderRow: {
    backgroundColor: "#fff6fa",
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#f2e2e8",
    gap: 6,
  },
  settlementRow: {
    backgroundColor: "#fff6fa",
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#f2e2e8",
    gap: 8,
  },
  orderRowMain: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
  },
  orderRowId: {
    color: "#9d174d",
    fontWeight: "700",
    flex: 1,
    textAlign: "right",
  },
  orderRowItems: {
    color: "#9a5e88",
    fontWeight: "600",
    width: 90,
    textAlign: "left",
  },
  orderRowTotal: {
    color: "#9d174d",
    fontWeight: "800",
    textAlign: "right",
  },
  orderRowMeta: {
    color: "#7d4f69",
    fontWeight: "600",
    fontSize: 13,
    textAlign: "right",
  },
  orderRowHint: {
    color: "#9d174d",
    fontWeight: "700",
    fontSize: 11,
    textAlign: "left",
  },
  syncedText: {
    color: "#9a5e88",
    fontWeight: "700",
    textAlign: "left",
  },
  pendingText: {
    color: "#ec4899",
    fontWeight: "700",
    textAlign: "left",
  },
  storeTableTitle: {
    marginTop: 14,
    marginBottom: 8,
    color: "#9d174d",
    textAlign: "right",
    fontWeight: "800",
    fontSize: 16,
  },
  dashboardRow: {
    backgroundColor: "#fff5f9",
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#f0dfe6",
  },
  dashboardStoreName: {
    color: "#9d174d",
    fontWeight: "800",
    fontSize: 15,
    textAlign: "right",
  },
  invoiceOverlay: {
    flex: 1,
    backgroundColor: "rgba(20, 20, 20, 0.42)",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 24,
  },
  invoiceCard: {
    backgroundColor: "#fffafd",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#f0d8e4",
    maxHeight: "90%",
    gap: 8,
  },
  datePickerModalCard: {
    backgroundColor: "#fffafd",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#f0d8e4",
    gap: 8,
  },
  mobileNavOverlayRoot: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  mobileNavBackdropTap: {
    ...StyleSheet.absoluteFillObject,
  },
  mobileNavBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(20, 20, 20, 0.42)",
  },
  mobileNavDrawer: {
    backgroundColor: "#fffafd",
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 18,
    padding: 14,
    borderLeftWidth: 1,
    borderColor: "#f0d8e4",
    height: "100%",
    gap: 8,
    boxShadow: "-4px 0px 16px rgba(0, 0, 0, 0.12)",
    elevation: 8,
  },
  mobileNavList: {
    flex: 1,
  },
  mobileNavItem: {
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: "#fff6fa",
    borderWidth: 1,
    borderColor: "#f2e2e8",
    marginBottom: 8,
  },
  mobileNavItemActive: {
    backgroundColor: "#f4d9e7",
    borderColor: "#efcad4",
  },
  mobileNavItemLabel: {
    color: "#9d174d",
    fontWeight: "800",
    textAlign: "right",
    fontSize: 14,
  },
  mobileNavItemLabelActive: {
    color: "#7a123a",
  },
  mobileNavItemSubLabel: {
    color: "#a77097",
    textAlign: "right",
    fontSize: 11,
    marginTop: 2,
  },
  mobileNavItemSubLabelActive: {
    color: "#9d174d",
  },
  datePickerConfirmButton: {
    backgroundColor: "#ec4899",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  datePickerConfirmText: {
    color: "#ffffff",
    fontWeight: "800",
  },
  invoiceItemsList: {
    maxHeight: 260,
  },
  footerStatus: {
    backgroundColor: "#9d174d",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginTop: 4,
  },
  footerStatusText: {
    color: "#fff3f8",
    textAlign: "right",
    fontWeight: "600",
    fontSize: 12,
  },
});
